Issue#1 - Create the project with current environment and base architecture
ios-course/swiftcowboys-team-project pull request #30
Opened 2023-05-06 08:22 UTC by nek-to

## What?
I created a project for Sleep Tracker application with folders for the chosen MVVM architecture and configured crypts for SwiftLint and SwiftFormat. Also added .gitignore settings. All of the necessary rules for the environment settings I took from [issue#1](https://github.com/ios-course/swiftcowboys-team-project/issues/1). Also add test modules.

## Why?
Removing the blocking factor for the team. You can start working on the implementation of the project.

2023-05-06 09:06 UTC, marinkman requested changes
I didn't see the file `CHANGELOG.md`.

2023-05-06 09:21 UTC, marinkman commented
And [@dersim-davaod](https://github.com/dersim-davaod) will still watch movies.

2023-05-06 09:49 UTC, MikhailKosarev commented on Sleep Tracker/Sleep TrackerTests/Sleep_TrackerTests.swift
> +//
there wasn't `add tests` in the description of the issue, but I think we shouldn't remove it from the project.

2023-05-06 10:05 UTC, nek-to commented on Sleep Tracker/Sleep TrackerTests/Sleep_TrackerTests.swift
> +//
In yesterday's discussion, Dersim made the point that any code can only be pushed with documentation and tests. Everyone agreed with this, but no one put it on the protocol. Should I now remove the tests?

2023-05-06 10:07 UTC, nek-to commented on Sleep Tracker/Sleep Tracker.xcodeproj/xcuserdata/kolyagribok.xcuserdatad/xcschemes/xcschememanagement.plist
> +<?xml version="1.0" encoding="UTF-8"?>
Deleted.

2023-05-06 10:07 UTC, nek-to commented on Sleep Tracker/Sleep Tracker/Application/SleepTrackerApp.swift
> +//
Done.

2023-05-06 10:23 UTC, MikhailKosarev requested changes
Suggest some improvements and have some questions:

2023-05-06 10:23 UTC, MikhailKosarev commented on Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
> +			shellScript = "if [[ \"$(uname -m)\" == arm64 ]]; then\n    export PATH=\"/opt/homebrew/bin:$PATH\"\nfi\n\nif which swiftlint > /dev/null; then\n  swiftlint\nelse\n  echo \"warning: SwiftLint not
I tried to test `SwiftLint' and it seems that our rules don't work:
<img width="781" alt="image" src="https://user-images.githubusercontent.com/100238123/236617524-14c3f81f-adf1-462e-92f9-8fe4ee322146.png">
Try to add the path to our rules in the script settings:
<img width="810" alt="image" src="https://user-images.githubusercontent.com/100238123/236617577-ce4dc6be-ab2b-4ce3-90f1-5886fa13c198.png">

2023-05-06 10:23 UTC, MikhailKosarev commented on Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
> +			shellScript = "if which swiftformat >/dev/null; then\n  swiftformat .\nelse\n  echo \"warning: SwiftFormat not installed, download from https://github.com/nicklockwood/SwiftFormat\"\nfi\n";
It doesn't seem to be working. Who installed `SwiftFormat` at the build stage and can check if the settings are correct?

2023-05-06 10:23 UTC, MikhailKosarev commented on Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
> +				CURRENT_PROJECT_VERSION = 1;
according to the description we need to remove the version.

2023-05-06 10:23 UTC, MikhailKosarev commented on Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 16.4;
please check the `project settings` section in the problem description. It looks like it is not configured at all :)

2023-05-06 10:23 UTC, MikhailKosarev commented on Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
> +				0B5026052A06424E004E3671 /* Models */,
`git` can't push empty directories. It can only track files:
<img width="161" alt="image" src="https://user-images.githubusercontent.com/100238123/236618139-41ed9b14-3c31-4cd5-abb4-03dec502ea78.png">

Please use [`.gitkeep` file](https://www.freecodecamp.org/news/what-is-gitkeep/) to solve the issue.

2023-05-06 10:26 UTC, nek-to commented on Sleep Tracker/Sleep Tracker/Application/SleepTrackerApp.swift
> +//  Sleep Tracker
Only that you have to cover the space with the \ sign when you call it in the terminal.

2023-05-06 10:34 UTC, nek-to commented on Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
> +			shellScript = "if [[ \"$(uname -m)\" == arm64 ]]; then\n    export PATH=\"/opt/homebrew/bin:$PATH\"\nfi\n\nif which swiftlint > /dev/null; then\n  swiftlint\nelse\n  echo \"warning: SwiftLint not
Fixed.

2023-05-06 10:34 UTC, nek-to commented on Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
> +			shellScript = "if which swiftformat >/dev/null; then\n  swiftformat .\nelse\n  echo \"warning: SwiftFormat not installed, download from https://github.com/nicklockwood/SwiftFormat\"\nfi\n";
Add .swift-version file. Now it should work.

2023-05-06 10:36 UTC, nek-to commented on Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
> +				CURRENT_PROJECT_VERSION = 1;
Where is this in description for issue#1?

2023-05-06 10:37 UTC, nek-to commented on Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 16.4;
Fixed.

2023-05-06 10:37 UTC, MikhailKosarev commented on Sleep Tracker/Sleep TrackerTests/Sleep_TrackerTests.swift
> +//
I vote for leaving tests

2023-05-06 10:37 UTC, marinkman commented on Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
> +			shellScript = "if [[ \"$(uname -m)\" == arm64 ]]; then\n    export PATH=\"/opt/homebrew/bin:$PATH\"\nfi\n\nif which swiftlint > /dev/null; then\n  swiftlint\nelse\n  echo \"warning: SwiftLint not
Please check that SwiftLint work properly. 
It may be worth adding the path to the rules.
For example:
```
export PATH="$PATH:/opt/homebrew/bin"
if which swiftlint > /dev/null; then
  swiftlint --config ../.swiftlint.yml
else
  echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
fi
```

2023-05-06 10:37 UTC, marinkman commented on Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
> +				CURRENT_PROJECT_VERSION = 1;
Version needs to be removed.

2023-05-06 10:37 UTC, marinkman commented on Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
> +				INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad = "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeR
iPhone only.

2023-05-06 10:37 UTC, marinkman commented on Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 16.4;
16.0

2023-05-06 10:39 UTC, nek-to commented on Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
> +				0B5026062A064259004E3671 /* Views */,
Are you going to keep only one View in the folder?

2023-05-06 10:40 UTC, nek-to commented on Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
> +				0B50260A2A0642A3004E3671 /* Application */,
Where do you define the application's startup file with the @main method then?

2023-05-06 10:41 UTC, nek-to commented on Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
> +			shellScript = "if [[ \"$(uname -m)\" == arm64 ]]; then\n    export PATH=\"/opt/homebrew/bin:$PATH\"\nfi\n\nif which swiftlint > /dev/null; then\n  swiftlint\nelse\n  echo \"warning: SwiftLint not
Fixed above.

2023-05-06 10:41 UTC, nek-to commented on Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
> +				CURRENT_PROJECT_VERSION = 1;
I don't see that in the description of issue#1.

2023-05-06 10:41 UTC, nek-to commented on Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
> +				INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad = "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeR
Fixed.

2023-05-06 10:42 UTC, nek-to commented on Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
> +				IPHONEOS_DEPLOYMENT_TARGET = 16.4;
Fixed.

2023-05-06 10:46 UTC, marinkman commented on Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
> +				CURRENT_PROJECT_VERSION = 1;
> - Create a project with the name "Sleep Tracker" with the settings below.
> - Set up SwiftFormat as part of the build phase and add the rules (below) to the root directory of the project.
> - Set up SwiftLint as part of the build phase and add the rules (below) to the root directory of the project.
> - `Remove the current version of the project.`
> - Add .gitignore file (details below).
> - Create the initial CHANGELOG.md (using the [keepChangelog](https://keepachangelog.com/en/1.0.0/) as the example) in the root directory of the project.
> - Create folder architecture.

2023-05-06 10:50 UTC, nek-to commented on Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
> +				0B5026052A06424E004E3671 /* Models */,
Done. Thx for information. I didn't know about this.

2023-05-06 10:56 UTC, marinkman commented on Sleep Tracker/Sleep Tracker.xcodeproj/xcuserdata/kolyagribok.xcuserdatad/xcschemes/xcschememanagement.plist
> +<?xml version="1.0" encoding="UTF-8"?>
I still see this folder.

2023-05-06 10:58 UTC, nek-to commented on Sleep Tracker/Sleep Tracker.xcodeproj/xcuserdata/kolyagribok.xcuserdatad/xcschemes/xcschememanagement.plist
> +<?xml version="1.0" encoding="UTF-8"?>
I still haven't requested a second review. I am still working on fixes to the project.

2023-05-06 10:59 UTC, nek-to commented on Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
> +				CURRENT_PROJECT_VERSION = 1;
Got it. I used old version of description. Done.

2023-05-06 11:07 UTC, marinkman commented on Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
> +				0B50260A2A0642A3004E3671 /* Application */,
It's not about the file. We didn't discuss creating an `Application` folder.

2023-05-06 11:11 UTC, marinkman commented on Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
> +				0B5026062A064259004E3671 /* Views */,
No, but I look at DoD in the issue#1 and see other folder names there.

2023-05-06 11:12 UTC, nek-to commented on Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
> +				0B50260A2A0642A3004E3671 /* Application */,
Okey, @MikhailKosarev   @meschya, what do u think, do we need Application folder or not?

2023-05-06 11:14 UTC, nek-to commented on Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
> +				0B5026062A064259004E3671 /* Views */,
So there no Test folders but some of mates think that we need to leave it.
@MikhailKosarev @meschya waiting for your opinion.

2023-05-06 11:40 UTC, nek-to commented
## Added :
- CHANGELOG.md
- .gitkeep for empty folders
- .swift-version

## FIxed:
- project settings

## Deleted:
- private folders
- current version
- comments

2023-05-06 11:46 UTC, marinkman commented on Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
> +			shellScript = "if which swiftformat >/dev/null; then\n  swiftformat .\nelse\n  echo \"warning: SwiftFormat not installed, download from https://github.com/nicklockwood/SwiftFormat\"\nfi\n";
Yes, it works now.

2023-05-06 11:54 UTC, MikhailKosarev commented on Sleep Tracker/Sleep Tracker/Application/SleepTrackerApp.swift
> +//  Sleep Tracker
ok

2023-05-06 11:58 UTC, MikhailKosarev commented on Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
> +				0B5026062A064259004E3671 /* Views */,
I think we should leave it as it is in the description. I see it not as a folder with views for example but as a folder with a `View` layer. That's why `View` instead of `Views`.

2023-05-06 12:00 UTC, MikhailKosarev commented on Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
> +			shellScript = "if which swiftformat >/dev/null; then\n  swiftformat .\nelse\n  echo \"warning: SwiftFormat not installed, download from https://github.com/nicklockwood/SwiftFormat\"\nfi\n";
Everything is working for you, right?
I just caught a warning...:
<img width="632" alt="image" src="https://user-images.githubusercontent.com/100238123/236622711-1d0af57d-6c7e-4a5f-b11f-e81412b2343c.png">

2023-05-06 12:02 UTC, MikhailKosarev commented on Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
> +				0B50260A2A0642A3004E3671 /* Application */,
We need to discuss what to do in such cases. I don't mind this folder, but it's not according to the description. Neither do the tests...

2023-05-06 12:06 UTC, nek-to commented on Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
> +				0B5026062A064259004E3671 /* Views */,
The projects I've worked on have always used these names. Including the project I'm working on now. [Another argument](https://stackoverflow.com/questions/39945727/best-practice-for-an-xcode-project-groups-structure). If you think this naming is incorrect and should be removed from it, put finger down emoji.

2023-05-06 12:07 UTC, marinkman commented on Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
> +			shellScript = "if which swiftformat >/dev/null; then\n  swiftformat .\nelse\n  echo \"warning: SwiftFormat not installed, download from https://github.com/nicklockwood/SwiftFormat\"\nfi\n";
Yes
I enter it:
```
enum Foo {
    case cat, dog
}
```
And I get it:
```
enum Foo {
    case cat
    case dog
}
```

2023-05-06 12:09 UTC, nek-to commented on Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
> +				0B50260A2A0642A3004E3671 /* Application */,
Because we can't get right and full description for now but in future.

2023-05-06 12:17 UTC, marinkman commented on Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
> +				CURRENT_PROJECT_VERSION = 1;
What about this?
<img width="727" alt="Screenshot 2023-05-06 at 15 13 45" src="https://user-images.githubusercontent.com/120239214/236623396-02c86d2a-ccdb-4945-a2b4-225c34dd5518.png">

2023-05-06 12:22 UTC, nek-to commented on Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
> +				CURRENT_PROJECT_VERSION = 1;
Do the project has a current version?

2023-05-06 12:25 UTC, MikhailKosarev commented on Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
> +			shellScript = "if which swiftformat >/dev/null; then\n  swiftformat .\nelse\n  echo \"warning: SwiftFormat not installed, download from https://github.com/nicklockwood/SwiftFormat\"\nfi\n";
@marinkman thanks for the example. It seems I have a local issue with `SwiftFormat`, that I need to fix on my mac :)
This conversation I mark as resolved.

2023-05-06 12:26 UTC, MikhailKosarev commented on Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
> +				CURRENT_PROJECT_VERSION = 1;
<img width="309" alt="image" src="https://user-images.githubusercontent.com/100238123/236623908-17595669-6b80-4f97-9088-91f3c9e46a31.png">

2023-05-06 12:28 UTC, marinkman commented on Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
> +				0B5026062A064259004E3671 /* Views */,
I don't have a clear opinion on this. I have nothing against any of the names. We just need to decide what is best.

2023-05-06 12:28 UTC, nek-to commented on Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
> +				CURRENT_PROJECT_VERSION = 1;
Please, don't double your note's...
Look at the my conversation with @marinkman about it.

2023-05-06 12:30 UTC, nek-to commented on Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
> +				0B5026062A064259004E3671 /* Views */,
Same as me.
We need to discuss this in Slack.

2023-05-06 12:50 UTC, marinkman commented on Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
> +				CURRENT_PROJECT_VERSION = 1;
Do you think it should be left?

2023-05-06 12:53 UTC, nek-to commented on Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
> +				CURRENT_PROJECT_VERSION = 1;
Please, answer to my question. Project has current version field?

2023-05-06 13:30 UTC, marinkman commented on Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
> +				CURRENT_PROJECT_VERSION = 1;
I understand that this wasn't described in detail in the issue.
That's why I'm asking for your opinion.

2023-05-06 13:45 UTC, marinkman commented on Sleep Tracker/Sleep TrackerTests/Sleep_TrackerTests.swift
> +//
I agree that we can leave the tests.

2023-05-06 13:55 UTC, dersim-davaod approved these changes
@nek-to Unfortunately, I can't effectively review all these changes within reasonable amount of time. LGTM from my side just to unblock merging.

2023-05-07 07:59 UTC, nek-to commented
## Changing's
- Renamed folders
- Deleted Application folder
- Deleted Current version everywhere

2023-05-07 09:02 UTC, marinkman reviewed
Looks much better overall.
But I didn't see the deletion of the current version.
And you missed the `Views` folder when renaming.

2023-05-07 11:54 UTC, nek-to commented
Because I still haven't heard any arguments or a unified opinion on this from the team.
I'll check the version, I've deleted in all of the targets. Although the description only mentions deletion in the project.

2023-05-07 12:06 UTC, marinkman commented
Then I don't understand why you renamed the rest of the folders.
In your [comment](https://github.com/ios-course/swiftcowboys-team-project/pull/30#issuecomment-1537351443)  you say that you deleted the current version everywhere, but I don't see it.

2023-05-07 12:13 UTC, nek-to commented
Everywhere it says in the description.
Renamed it so that it corresponds to the common practices to which I referred. Would anyone have an argument for naming them the same as in the description?
Note that the task is no longer as described, but some people agree with some of the changes. Are we going to block the task further or finally come to a consensus, edit the description, etc. ?

2023-05-07 22:12 UTC, MikhailKosarev requested changes
Just one small issue

2023-05-07 22:12 UTC, MikhailKosarev commented on Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
> +		0B50260B2A084FE0004E3671 /* Sleep-TrackerTests-Info.plist */ = {isa = PBXFileReference; lastKnownFileType = text.plist; path = "Sleep-TrackerTests-Info.plist"; sourceTree = SOURCE_ROOT; };
It looks like there is no such a file:
<img width="198" alt="image" src="https://user-images.githubusercontent.com/100238123/236704949-38cd17b2-5208-48df-ab26-50bb125512b8.png">

2023-05-07 22:54 UTC, nek-to commented on Sleep Tracker/Sleep Tracker.xcodeproj/project.pbxproj
> +		0B50260B2A084FE0004E3671 /* Sleep-TrackerTests-Info.plist */ = {isa = PBXFileReference; lastKnownFileType = text.plist; path = "Sleep-TrackerTests-Info.plist"; sourceTree = SOURCE_ROOT; };
Hello from merge conflict

2023-05-08 09:00 UTC, marinkman commented
I don't understand. Why did this file appear? And is it needed here?

<img width="347" alt="Screenshot 2023-05-08 at 11 44 43" src="https://user-images.githubusercontent.com/120239214/236779044-c0d92826-a7f2-4458-a6d8-de55b71246da.png">

2023-05-08 10:43 UTC, nek-to commented
> I don't understand. Why did this file appear? And is it needed here?
> 
> <img alt="Screenshot 2023-05-08 at 11 44 43" width="347" src="https://user-images.githubusercontent.com/120239214/236779044-c0d92826-a7f2-4458-a6d8-de55b71246da.png">

As I wrote **above**, this was the result of the merge conflict solution. I'll see if it affects anything. It did at night.

2023-05-08 10:51 UTC, nek-to commented
Removed the Test plist. The functionality of the build is preserved.

2023-05-08 11:04 UTC, marinkman approved these changes
LGTM

2023-05-08 11:13 UTC, MikhailKosarev approved these changes
LGTM

2023-05-08 11:15 UTC, nek-to commented
Merge with the main branch of an empty project.

2023-05-08 11:15 UTC, merged