Issue#28 - create `Color` extension and `Custom` enum
ios-course/swiftcowboys-team-project pull request #37
Opened 2023-05-09 08:09 UTC by marinkman

## What?

- Created `Color` extension
- Created `Custom` enum and filled with `static let` colors according to the [Project color scheme](https://github.com/ios-course/swiftcowboys-team-project/wiki/Project-color-scheme)
- Created `CustomColorTests` class to tests `Custom` enum

## Why?
According to issue #28  

## Anything Else?
Need to discuss folder/file structure in test targets.

2023-05-09 17:08 UTC, nek-to commented
I like your code. Honestly, I started the implementation the same way you did. I have no questions about the documentation and the tests. They may not be complete but they look good to me. The only thing is that in DoD we are told to create an Enum of Colors and you have an Extension created. I think if everyone agrees, you could tweak it.

That's the only blocking factor for LGTM from me.

2023-05-09 17:26 UTC, MikhailKosarev commented on Sleep Tracker/Sleep Tracker/Helpers/Color+Extension.swift
> +    /// A custom color representation that adapts to the given context.
According to the use of this extension "AppScheme" seems most appropriate - e.g. `Color.AppScheme.darkIndigo`

2023-05-09 17:41 UTC, marinkman commented
@MikhailKosarev Why don't you support this idea?

2023-05-09 19:28 UTC, marinkman commented
@MikhailKosarev It doesn't take long. I've already done it.

2023-05-09 19:29 UTC, marinkman commented on Sleep Tracker/Sleep Tracker/Helpers/Color+Extension.swift
> +import SwiftUI
That's really better.
Done.

2023-05-09 19:32 UTC, marinkman commented on Sleep Tracker/Sleep TrackerUITests/CustomColorTests.swift
> +final class CustomColorTests: XCTestCase {
Yes, it is needed. Test added.

2023-05-09 21:06 UTC, MikhailKosarev approved these changes
LGTM

2023-05-09 21:06 UTC, MikhailKosarev commented on Sleep Tracker/Sleep TrackerUITests/AppSchemeTests.swift
> +        XCTAssertTrue(isTheColorUsed(color: Color.AppScheme.darkIndigo))
just for info, we can you this way:
```suggestion
        XCTAssertTrue(isTheColorUsed(color: .AppScheme.darkIndigo))
```

2023-05-09 22:25 UTC, dersim-davaod requested changes
Please consider one more little thing:

2023-05-10 07:43 UTC, marinkman commented on Sleep Tracker/Sleep TrackerUITests/AppSchemeTests.swift
> +        XCTAssertTrue(isTheColorUsed(color: Color.AppScheme.darkIndigo))
Yes, exactly, thanks.
Done it.

2023-05-10 07:49 UTC, marinkman commented on Sleep Tracker/Sleep TrackerUITests/AppSchemeTests.swift
> +import SwiftUI
Yes, thanks. 
I created a `Helpers` folder in the test target and renamed the file `AppSchemeTeests` to `Color+AppSchemeTests`.

2023-05-10 07:50 UTC, dersim-davaod approved these changes
LGTM

2023-05-10 10:39 UTC, merged