Issue#23 - create `SleepSetupView`
ios-course/swiftcowboys-team-project pull request #39
Opened 2023-05-09 15:59 UTC by meschya

## What?

- Created `SleepPageView` folder
- Created `SleepSetupView` file
- Created `AlarmButton` and animation when pressing
- Created `TimePicker`

## Why?
According to issue #23

2023-05-09 18:25 UTC, MikhailKosarev reviewed
It looks great! Just like in Figma. I have a few questions and suggestions:

2023-05-09 18:25 UTC, MikhailKosarev commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView.swift
> +    // MARK: - Alarm Button
nit: I know, we didn't discuss such rules :) but can you explain why did you use `MARK` comment before each view? It looks like a duplication of information.
<img width="182" alt="image" src="https://github.com/ios-course/swiftcowboys-team-project/assets/100238123/5ede2c0e-dd01-40b9-94fa-978121402279">

2023-05-09 18:25 UTC, MikhailKosarev commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView.swift
> +    // MARK: - Properties
Will it be better to use just two `MARK` comments? `Public interface` and `Private interface`? What do you think?

2023-05-09 18:25 UTC, MikhailKosarev commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView.swift
> +    @State var animate = false
internal property in the `private` section :)

2023-05-10 05:28 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView.swift
> +    // MARK: - Alarm Button
I agree, we didn't discuss it, so I corrected it

2023-05-10 05:29 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView.swift
> +    @State var animate = false
This question on `Mark` will have to be brought up for general discussion

2023-05-10 05:32 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView.swift
> +                    .zIndex(1)
There was a problem with the `DatePicker` overlaying the `AlarmButton` and cutting it in half, so the button only pressed the left side

`zIndex()` allowed the `DatePicker` to be lower than the `AlarmButton`

2023-05-10 05:34 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView.swift
> +    // MARK: - Properties
This question on `Mark` will have to be brought up for general discussion

2023-05-10 08:38 UTC, marinkman reviewed
Looks great overall.
I have a question about `TimePicker`: 
It seems to me or we discussed the 24-hour time format?

2023-05-10 09:04 UTC, meschya commented
> Looks great overall. I have a question about `TimePicker`: It seems to me or we discussed the 24-hour time format?

The `DatePicker` is in the format of the user device. So if the user has 12 hour then shows time AM/PM if user set to 24 then shows that. The simulator will show AM/PM as that is USA. Try on real device that in 24. hours to see it.

2023-05-10 09:30 UTC, marinkman commented
> > Looks great overall. I have a question about `TimePicker`: It seems to me or we discussed the 24-hour time format?
> 
> The `DatePicker` is in the format of the user device. So if the user has 12 hour then shows time AM/PM if user set to 24 then shows that. The simulator will show AM/PM as that is USA. Try on real device that in 24. hours to see it.

Thanks for the info, I didn't know that.

2023-05-10 09:40 UTC, marinkman commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView.swift
> +    // MARK: - Properties
I agree with @MikhailKosarev about the separation of interfaces.

2023-05-10 09:49 UTC, marinkman approved these changes
LGTM overall.
Only I would like to see `MARK:`  `Public interface` and `Private interface`.

2023-05-10 11:50 UTC, dersim-davaod requested changes
Please consider improvements:

2023-05-10 11:50 UTC, dersim-davaod commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView.swift
> +struct SleepSetupView: View {
Missing doc.

2023-05-10 11:50 UTC, dersim-davaod commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView.swift
> +    @State var animate = false
Missing doc.

Please review the rest of code.

2023-05-10 11:50 UTC, dersim-davaod commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView.swift
> +            Image("Sleeping_astronaut_image")
I'd like to have typed image names. Smth like:

```suggestion
            Image(.astronautImage)
```

Otherwise, it's easy to have a typo plus we follow the DRY principle.

2023-05-10 11:50 UTC, dersim-davaod commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView.swift
> +                    .padding(.leading, 40)
Magic numbers.
Please review the rest of code.

2023-05-10 11:50 UTC, dersim-davaod commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView.swift
> +    private var timePicker: some View {
I'd suggest to extract Views into the separate struct/files.

2023-05-10 11:50 UTC, dersim-davaod commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView.swift
> +        Text("estimated bedtime 7:52")
Is that an estimated time when we supposed to go to bed?

2023-05-10 11:50 UTC, dersim-davaod commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView.swift
> +    private var timePicker: some View {
Should we allow to edit the time picker only when the alarm is enabled? 

As an option: to enable alarm if the time was changed using the time picker.

UPD: according to the mockups, we shouldn't display a time picker if an alarm is off.

2023-05-15 20:12 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView.swift
> +struct SleepSetupView: View {
fixed

2023-05-15 20:37 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView.swift
> +    @State var animate = false
fixed

2023-05-15 20:37 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView.swift
> +            Image("Sleeping_astronaut_image")
fixed

2023-05-15 20:38 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView.swift
> +    private var timePicker: some View {
I don't understand why put it in a separate struct/files, because it won't be reused.

2023-05-15 20:40 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView.swift
> +        Text("estimated bedtime 7:52")
At this point it is a static value. There is a separate issue in which there is a task to add logic to a given time.

2023-05-15 20:41 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView.swift
> +    private var timePicker: some View {
fixed

2023-05-15 22:03 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView.swift
> +                    .padding(.leading, 40)
fixed

2023-05-16 16:11 UTC, dersim-davaod requested changes
Didn't a quick review.
Will complete the review later.

Currently please consider improvements and make sure you have decomposed Views.

2023-05-16 20:47 UTC, MikhailKosarev commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView.swift
> + A view showing the option to set the alarm clock and set the wake-up time before going to bed.
nit: and you can remove the mention that it is a view

2023-05-16 20:49 UTC, MikhailKosarev commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView.swift
> +        Text("estimated bedtime 7:52")
@dersim-davaod why not? The format is as we discussed with the team

2023-05-16 20:51 UTC, dersim-davaod commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView.swift
> +        Text("estimated bedtime 7:52")
That was not my question?
I'm trying to ask: what the label shows? What is the semantics of the text?

2023-05-16 20:53 UTC, MikhailKosarev commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView.swift
> +     Creating an image with an astronaut.
We haven't discussed it, but in general, we all have to document at least according to [API design guidelines](https://www.swift.org/documentation/api-design-guidelines/)

2023-05-16 21:03 UTC, MikhailKosarev requested changes
I agree with Dersim's comments and additionally consider some improvements:

2023-05-17 08:23 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView.swift
> + A view showing the option to set the alarm clock and set the wake-up time before going to bed.
fixed

2023-05-17 08:23 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView.swift
> +    private var sleepingAstronautImage: some View {
fixed

2023-05-17 08:24 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView.swift
> +            .frame(width: 150, height: 150)
fixed

2023-05-17 08:24 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView.swift
> +    private var alarmButton: some View {
fixed

2023-05-17 08:24 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView.swift
> +            sleepingAstronautImage
fixed

2023-05-17 08:25 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView.swift
> +        Text("No alarm,\nonly sleep analized")
fixed

2023-05-17 08:25 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView.swift
> +     Boolean value by which we can know if the alarm is on or off
fixed

2023-05-17 08:25 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView.swift
> +     Creating an image with an astronaut.
fixed

2023-05-17 08:25 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView.swift
> +     Creating an image with an astronaut.
fixed

2023-05-17 09:24 UTC, marinkman commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView.swift
> +                    .padding(.leading, 40)
- #54

2023-05-17 09:35 UTC, marinkman commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView.swift
> +        Text("estimated bedtime 7:52")
Based on the current time and time on which the alarm is set, this label show how long the user will sleep.

2023-05-17 10:28 UTC, marinkman requested changes
Consider some improvements:

2023-05-17 10:28 UTC, marinkman commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView/HelpersView/AlarmButton.swift
> +/// A custom button for the alarm clock which, when clicked, change its opacity property with animation.
I can't click on it.

2023-05-17 10:28 UTC, marinkman commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView/HelpersView/SleepTimePicker.swift
> +    /// A boolean value when the TimePicker show or hide.
I'd suggest:

```suggestion
    /// A boolean value that indicates whether the TimePicker is hidden.
```

2023-05-17 10:28 UTC, marinkman commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView/SleepSetupView.swift
> +    /// Boolean value by which we can know if the alarm is on or off.
```suggestion
    /// Boolean value that indicates whether the alarm is on.
```

2023-05-17 10:28 UTC, marinkman commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView/SleepSetupView.swift
> +/// A view show the option to set the alarm clock and set the wake-up time before go to bed.
nit: 

Maybe that would be better?

```suggestion
/// A view shows the options that the user can set before go to bed.
```

2023-05-17 10:28 UTC, marinkman commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView/HelpersView/SleepTimePicker.swift
> +struct SleepTimePicker: View {
```suggestion
struct AlarmTimePickerView: View {
```

2023-05-17 10:28 UTC, marinkman commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView/HelpersView/AlarmButton.swift
> +struct AlarmButton: View {
We need a different name. It's not a button, it's just a shape with an image.

2023-05-17 10:38 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView/HelpersView/AlarmButton.swift
> +    /// A boolean value that indicates when the animation is on or off.
fixed

2023-05-17 10:40 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView/HelpersView/AlarmButton.swift
> +/// A custom button for the alarm clock which, when clicked, change its opacity property with animation.
Hmm, I don't have that problem 🙁

2023-05-17 10:40 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView/HelpersView/SleepTimePicker.swift
> +    /// A boolean value when the TimePicker show or hide.
fixed

2023-05-17 10:41 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView/SleepSetupView.swift
> +/// A view show the option to set the alarm clock and set the wake-up time before go to bed.
I agree, fixed

2023-05-17 10:44 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView/HelpersView/AlarmButton.swift
> +struct AlarmButton: View {
fixed

2023-05-17 13:55 UTC, marinkman requested changes

2023-05-17 13:55 UTC, marinkman commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/HelpersView/RoundedAlarmView.swift
> +struct AlarmButton_Previews: PreviewProvider {
```suggestion
struct RoundedAlarmView_Previews: PreviewProvider {
```

2023-05-17 13:55 UTC, marinkman commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/SleepSetupView.swift
> +        Text("No alarm clock,\njust analyzed sleep")
```suggestion
        Text("No alarm clock,\njust a sleep analysis")
```

2023-05-17 13:57 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/HelpersView/AlarmTimePickerView.swift
> +struct SleepTimePicker_Previews: PreviewProvider {
fixed

2023-05-17 14:08 UTC, dersim-davaod requested changes
Please consider improvements.
Please simplify the code and make sure the "subviews" are independent of "superviews".

2023-05-17 14:08 UTC, dersim-davaod commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/HelpersView/RoundedAlarmView.swift
> +            .zIndex(1)
Can we simplify the code:

```suggestion
        Image.AppImage.alarmSymbolWhite
            .padding(EdgeInsets(top: 10, leading: 25, bottom: 10, trailing: 25))
            .background(.purple)
            .cornerRadius(30)
            .opacity(animate ? 1.0 : 0.5)
```

?

2023-05-17 14:08 UTC, dersim-davaod commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/SleepSetupView.swift
> +                }
Can we have a "secondary view" where depends on the alarm state we show either `TimePickerView` or `Label`?

2023-05-17 14:08 UTC, dersim-davaod commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/HelpersView/AlarmTimePickerView.swift
> +            .padding(.leading, 40)
Why we have padding here?

2023-05-17 14:08 UTC, dersim-davaod commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/HelpersView/AlarmTimePickerView.swift
> +            .zIndex(0)
Why we have zIndex here?

2023-05-17 14:09 UTC, dersim-davaod commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView.swift
> +    private var timePicker: some View {
Regarding separate structs: It makes code easier to read and understand. Do you have other opinion?
Regarding separate files: previously we had an agreeement "one type - one file".

2023-05-17 14:11 UTC, dersim-davaod commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView.swift
> +        Text("estimated bedtime 7:52")
Ok, but the format "8:15" looks like the exact time, not the duration.
Also if I try to translate the text, I will get "Расчетное время отхода ко сну".
That's confusing.

2023-05-17 14:12 UTC, dersim-davaod commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView.swift
> +            sleepingAstronautImage
I still see the same nits in the latest implementation.

2023-05-17 14:15 UTC, dersim-davaod commented
Please do not forget to fix the conflicts before re-requesting review.

2023-05-17 14:19 UTC, marinkman commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView.swift
> +        Text("estimated bedtime 7:52")
I agree, `Estimated sleep duration` would be better.

2023-05-17 20:49 UTC, MikhailKosarev commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView.swift
> +                    .zIndex(1)
Try to search the info on how to refactor it or ask in the Slack

2023-05-17 20:54 UTC, MikhailKosarev requested changes
Consider some improvements and agree with other reviewers

2023-05-18 07:38 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/HelpersView/AlarmTimePickerView.swift
> +    // MARK: - Public interface
fixed

2023-05-18 07:39 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/HelpersView/AlarmTimePickerView.swift
> +    /// When `true` TimePicker is hide and when `false` TimePicker is show.
fixed

2023-05-18 07:40 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/HelpersView/AlarmTimePickerView.swift
> +        DatePicker("", selection: $currentDate, displayedComponents: .hourAndMinute)
fixed

2023-05-18 07:43 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/HelpersView/AlarmTimePickerView.swift
> +            .datePickerStyle(.wheel)
We decided to find a new approach to time selection in our app, so we turned our attention to the wheel picker, because in our opinion it is more convenient

2023-05-18 08:30 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/HelpersView/RoundedAlarmView.swift
> +/// A custom button for the alarm clock which, when clicked, change its opacity property with animation.
fixed

2023-05-18 08:32 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/HelpersView/RoundedAlarmView.swift
> +struct RoundedAlarmView: View {
this button will be the only instance in the application and will be responsible for the alarm clock, I think that it is not quite right to give the possibility to change the image in it

2023-05-18 08:35 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/HelpersView/RoundedAlarmView.swift
> +            .zIndex(1)
I agree
fixed

2023-05-18 08:55 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/HelpersView/AlarmTimePickerView.swift
> +            .frame(width: 200, height: 100)
fixed

2023-05-18 08:55 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/HelpersView/RoundedAlarmView.swift
> +            .zIndex(1)
fixed

2023-05-18 09:02 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/HelpersView/RoundedAlarmView.swift
> +    /// When `true` button has no transparency and when `false` button has transparency.
fixed

2023-05-18 09:02 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/HelpersView/RoundedAlarmView.swift
> +    @Binding var animate: Bool
fixed

2023-05-18 09:07 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/SleepSetupView.swift
> +                }
fixed

2023-05-18 09:07 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/HelpersView/AlarmTimePickerView.swift
> +            .padding(.leading, 40)
fixed

2023-05-18 09:09 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/HelpersView/AlarmTimePickerView.swift
> +            .zIndex(0)
fixed

2023-05-18 10:44 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/HelpersView/AlarmTimePickerView.swift
> +    @State private var currentDate = Date()
fixed

2023-05-18 19:59 UTC, marinkman requested changes
Consider some improvements:

2023-05-18 19:59 UTC, marinkman commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/Subviews/AlarmTimePickerView.swift
> +/// A custom TimePicker in which the user will be able to choose what time he wakes up.
```suggestion
/// A TimePicker in which the user can select the wake up time.
```

2023-05-18 19:59 UTC, marinkman commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/Subviews/AlarmTimePickerView.swift
> +    /// A variable that returns the date selected in TimePicker.
```suggestion
    /// A date selected in the TimePicker.
```

2023-05-18 19:59 UTC, marinkman commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/Subviews/EstimatedLabel.swift
> +struct EstimatedLabel: View {
```suggestion
struct EstimatedLabelView: View {
```

2023-05-18 19:59 UTC, marinkman commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/Subviews/EstimatedLabel.swift
> +/// A view showing how long the user will sleep.
```suggestion
/// A view that shows the predicted duration of sleep.
```

2023-05-18 19:59 UTC, marinkman commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/Subviews/EstimatedLabel.swift
> +        Text("estimated bedtime 07:52")
```suggestion
        Text("Predicted sleep duration:\n07:52")
```

2023-05-18 19:59 UTC, marinkman commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/Subviews/NoAlarmLabel.swift
> +/// A view that display information that the alarm clock is off.
```suggestion
/// A view that shows information about the disabled alarm clock.
```

2023-05-18 19:59 UTC, marinkman commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/Subviews/RoundedAlarmView.swift
> +    /// And when takes the value `false` rectangular rounded view has transparency.
Something like that:
```suggestion
    /// A boolean value that indicates whether the alarm is animated.
    /// When `true` alarm is animated and when `false` alarm is not animated.

2023-05-19 05:41 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/Subviews/AlarmSetupView.swift
> +    /// A variable that returns the date selected in TimePicker.
fixed

2023-05-19 05:42 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/Subviews/AlarmTimePickerView.swift
> +/// A custom TimePicker in which the user will be able to choose what time he wakes up.
fixed

2023-05-19 05:42 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/Subviews/AlarmTimePickerView.swift
> +    /// A variable that returns the date selected in TimePicker.
fixed

2023-05-19 05:42 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/Subviews/EstimatedLabel.swift
> +struct EstimatedLabel: View {
fixed

2023-05-19 05:42 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/Subviews/EstimatedLabel.swift
> +/// A view showing how long the user will sleep.
fixed

2023-05-19 05:43 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/Subviews/EstimatedLabel.swift
> +        Text("estimated bedtime 07:52")
fixed

2023-05-19 05:43 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/Subviews/NoAlarmLabel.swift
> +/// A view that display information that the alarm clock is off.
fixed

2023-05-19 05:44 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/Subviews/RoundedAlarmView.swift
> +    /// And when takes the value `false` rectangular rounded view has transparency.
fixed

2023-05-19 11:47 UTC, dersim-davaod requested changes
Please resolve conflicts first.

2023-05-19 13:32 UTC, dersim-davaod requested changes
Please consider improvements to improve maintainability.

2023-05-19 13:32 UTC, dersim-davaod commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/Subviews/RoundedAlarmView.swift
> +            .cornerRadius(52)
What's the purpose of such corner radius. Seems everything >= 20 has the same look and feel. Am I missing something?

2023-05-19 13:32 UTC, dersim-davaod commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/Subviews/NoAlarmLabel.swift
> +            .frame(minWidth: 0,
Why do you need these frame modifier here?

2023-05-19 13:32 UTC, dersim-davaod commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/Subviews/NoAlarmLabel.swift
> +            .frame(minWidth: 0,
Could you please explain why the label has the max height == 100?

2023-05-19 13:32 UTC, dersim-davaod commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/Subviews/EstimatedLabelView.swift
> +struct EstimatedLabelView: View {
nit:
```suggestion
struct EstimatedSleepTimeLabelView: View {
```
or
```suggestion
struct EstimatedSleepDurationLabelView: View {
```

2023-05-19 13:32 UTC, dersim-davaod commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/Subviews/NoAlarmLabel.swift
> +struct NoAlarmLabel: View {
nit:

```suggestion
struct NoAlarmLabelView: View {
```

(if you had such agreement)

2023-05-19 13:32 UTC, dersim-davaod commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/SleepSetupView.swift
> +                        withAnimation(Animation.spring().speed(1)) {
Do we need an animation at the moment?

2023-05-19 13:32 UTC, dersim-davaod commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/Subviews/AlarmSetupView.swift
> +    /// A date selected in the TimePicker.
Do you select a date? Does the user select a date?

2023-05-19 13:32 UTC, dersim-davaod commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/Subviews/AlarmSetupView.swift
> +    /// If `true` TimePicker is show, otherwise Label is show.
Could you please explain why this line should belong here?

Am I right that if you change the logic within the `body`, I should update the documentation for the `isAlarmOn`?

2023-05-19 13:40 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/Subviews/WheelTimePickerView.swift
> +/// A TimePicker with style wheel.
fixed

2023-05-19 13:41 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/Subviews/WheelTimePickerView.swift
> +/// A TimePicker with style wheel.
fixed

2023-05-19 13:43 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/Subviews/RoundedAlarmView.swift
> +    /// If `true` view is opaque, otherwise is semi-transparency.
fixed

2023-05-19 13:49 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/Subviews/NoAlarmLabel.swift
> +            .frame(minWidth: 0,
Label has a maximum height of 100 to match the size of `WheelTimePickerView` and not to jump when replacing UI components.

2023-05-19 13:49 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/Subviews/EstimatedLabelView.swift
> +struct EstimatedLabelView: View {
fixed

2023-05-19 13:50 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/Subviews/NoAlarmLabel.swift
> +struct NoAlarmLabel: View {
fixed

2023-05-19 13:51 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/SleepSetupView.swift
> +                        withAnimation(Animation.spring().speed(1)) {
no, we don't need animation here.
corrected

2023-05-19 13:56 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/Subviews/AlarmSetupView.swift
> +    /// A date selected in the TimePicker.
fixed

2023-05-19 14:05 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/Subviews/AlarmSetupView.swift
> +    /// If `true` TimePicker is show, otherwise Label is show.
This view is responsible for displaying `WheelTimePickerView` or `NoAlarmLabelView` and the boolean value lets `AlarmSetupView` know whether the alarm is on or not, so I think that rewriting the documentation will not be necessary

2023-05-19 14:12 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/Subviews/WheelTimePickerView.swift
> +    /// A date selected in the TimePicker.
For the user we select the time, but what actually comes is the date that we will format in the `viewModel`

2023-05-19 14:25 UTC, dersim-davaod commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/Subviews/AlarmSetupView.swift
> +    /// If `true` TimePicker is show, otherwise Label is show.
@marinkman @MikhailKosarev what do you think? Do you agree?

2023-05-19 15:57 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/Subviews/RoundedAlarmView.swift
> +            .cornerRadius(52)
fixed

2023-05-19 17:20 UTC, marinkman commented on Sleep Tracker/SleepTracker/View/SleepSetupView/Subviews/WheelTimePickerView.swift
> +    /// A date selected by the user in the Piker with time.
I don't like it.

> in the Piker with time.

2023-05-19 17:31 UTC, meschya commented on Sleep Tracker/SleepTracker/View/SleepSetupView/Subviews/WheelTimePickerView.swift
> +    /// A date selected by the user in the Piker with time.
What exactly don't you like?
And what can you offer?

2023-05-19 17:37 UTC, marinkman commented on Sleep Tracker/SleepTracker/View/SleepSetupView/Subviews/WheelTimePickerView.swift
> +    /// A date selected by the user in the Piker with time.
Wording.
in the time picker

2023-05-21 20:55 UTC, dersim-davaod commented
@meschya please make sure you have answered all the comments before re-requesting review.

2023-05-22 08:48 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/Subviews/AlarmSetupView.swift
> +    /// If `true` TimePicker is show, otherwise Label is show.
fixed

2023-05-22 08:50 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView.swift
> +            sleepingAstronautImage
My mistake, it's all fixed now

2023-05-22 08:51 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepPageView/SleepSetupView.swift
> +        Text("estimated bedtime 7:52")
Totally agree, corrected to `Predicted sleep duration`

2023-05-22 10:40 UTC, marinkman approved these changes
LGTM

2023-05-22 11:39 UTC, MikhailKosarev approved these changes
LGTM

2023-05-22 13:15 UTC, dersim-davaod requested changes
Unfortunately, I can't render the "SleepSetupView".

Also consider improvements and clarifications for the earlier conversations.

2023-05-22 13:15 UTC, dersim-davaod commented on Sleep Tracker/SleepTracker/View/SleepSetupView/Subviews/NoAlarmLabelView.swift
> +        Text("No alarm clock,\njust a sleep analysis")
nit:

Do we need a comma?
```suggestion
        Text("No alarm clock\njust a sleep analysis")
```

2023-05-22 15:24 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/Subviews/WheelTimePickerView.swift
> +    /// A date selected in the TimePicker.
we have discussed with team and decided to keep this name

2023-05-22 15:26 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/Subviews/RoundedAlarmView.swift
> +    /// If `true` view is opaque, otherwise is semi-transparency.
fixed

2023-05-22 15:27 UTC, meschya commented on Sleep Tracker/SleepTracker/View/SleepSetupView/Subviews/AlarmSetupView.swift
> +    }
fixed

2023-05-22 15:28 UTC, meschya commented on Sleep Tracker/SleepTracker/View/SleepSetupView/Subviews/NoAlarmLabelView.swift
> +        Text("No alarm clock,\njust a sleep analysis")
fixed

2023-05-22 15:41 UTC, meschya commented on Sleep Tracker/SleepTracker/View/SleepSetupView/Subviews/NoAlarmLabelView.swift
> +        Text("No alarm clock,\njust a sleep analysis")
fixed

2023-05-22 15:41 UTC, meschya commented on Sleep Tracker/Sleep Tracker/View/SleepSetupView/HelpersView/AlarmTimePickerView.swift
> +            .datePickerStyle(.wheel)
We discussed this with the team and decided to go with the `wheel style' because it seemed more convenient in this case.

2023-05-22 15:48 UTC, dersim-davaod approved these changes
LGTM

2023-05-22 15:49 UTC, merged