Issue#24 - `DuringSleepView`: create a view
ios-course/swiftcowboys-team-project pull request #40
Opened 2023-05-09 18:58 UTC by MikhailKosarev

## What?
- Created a `DuringSleepView` folder and appropriate SwiftUI file
- Fill the file with the UI according to the Figma

## Why?
- To close #24

2023-05-10 11:38 UTC, dersim-davaod requested changes
Consider improvements:

2023-05-10 11:38 UTC, dersim-davaod commented on Sleep Tracker/Sleep Tracker/View/DuringSleepView/DuringSleepView.swift
> +    // MARK: - Public interface
I see that you haven't run linters :) 
Please fix it.

2023-05-10 11:38 UTC, dersim-davaod commented on Sleep Tracker/Sleep Tracker/View/DuringSleepView/DuringSleepView.swift
> +            Image("Sleeping_astronaut_image")
I'd like to have typed image names. Smth like:

```suggestion
            Image(.astronautImage)
```

Otherwise, it's easy to have a typo plus we follow the DRY principle.

2023-05-10 11:38 UTC, dersim-davaod commented on Sleep Tracker/Sleep Tracker/View/DuringSleepView/DuringSleepView.swift
> +                .font(.system(size: 25))
nit: magic number.

2023-05-10 11:38 UTC, dersim-davaod commented on Sleep Tracker/Sleep Tracker/View/DuringSleepView/DuringSleepView.swift
> +                .foregroundColor(.white)
nit: magic colour.

2023-05-15 18:20 UTC, MikhailKosarev commented on Sleep Tracker/Sleep Tracker/View/DuringSleepView/DuringSleepView.swift
> +            Image("Sleeping_astronaut_image")
fixed

2023-05-15 18:22 UTC, MikhailKosarev commented on Sleep Tracker/Sleep Tracker/View/DuringSleepView/DuringSleepView.swift
> +                .font(.system(size: 25))
I can't fix it now, but we need to create an issue from this point. @marinkman I think we need to create an `AppFonts`, let's discuss it in Slack.

2023-05-15 18:22 UTC, MikhailKosarev commented on Sleep Tracker/Sleep Tracker/View/DuringSleepView/DuringSleepView.swift
> +                .foregroundColor(.white)
fixed

2023-05-15 18:22 UTC, MikhailKosarev commented on Sleep Tracker/Sleep Tracker/View/DuringSleepView/DuringSleepView.swift
> +    // MARK: - Public interface
of course :) fixed

2023-05-15 19:13 UTC, MikhailKosarev commented
> I think there's need to add a spacer between the picture and the text to make it look like a Figma sample.

I don't know exactly,  I have a thought that it might then stretch a lot. My suggestion is to leave it as it is and fix something after adding this view to the screen.

2023-05-15 20:20 UTC, marinkman approved these changes
LGTM

2023-05-15 21:32 UTC, dersim-davaod commented on Sleep Tracker/Sleep Tracker/View/DuringSleepView/DuringSleepView.swift
> +                .font(.system(size: 25))
Give the issue number please. This helps me to double-check you haven't forgot to create a ticket.

2023-05-16 08:11 UTC, marinkman commented on Sleep Tracker/Sleep Tracker/View/DuringSleepView/DuringSleepView.swift
> +                .font(.system(size: 25))
@dersim-davaod [issue#54](https://github.com/ios-course/swiftcowboys-team-project/issues/54)
A detailed description will be added after discussion.

2023-05-16 14:19 UTC, dersim-davaod requested changes
Consider minor improvements:

2023-05-16 14:19 UTC, dersim-davaod commented on Sleep Tracker/Sleep Tracker/View/DuringSleepView/DuringSleepView.swift
> +                .AppImage.sleepingAstronaut
nit:
```suggestion
            Image.AppImage.sleepingAstronaut
```

2023-05-16 14:26 UTC, MikhailKosarev commented on Sleep Tracker/Sleep Tracker/View/DuringSleepView/DuringSleepView.swift
> +                .AppImage.sleepingAstronaut
fixed

2023-05-16 14:35 UTC, dersim-davaod requested changes
Please check the rendered view and consider an improvement:

2023-05-16 14:39 UTC, MikhailKosarev commented on Sleep Tracker/Sleep Tracker/View/DuringSleepView/DuringSleepView.swift
> +                .foregroundColor(.AppScheme.white)
it's because the color of the text is white, according to the design in Figma. This view will be on a dark background. You can run `Color scheme options' in the preview.

2023-05-16 14:41 UTC, dersim-davaod commented on Sleep Tracker/Sleep Tracker/View/DuringSleepView/DuringSleepView.swift
> +                .foregroundColor(.AppScheme.white)
I have run the app and can't see the text. What should I do?

2023-05-16 15:27 UTC, MikhailKosarev commented on Sleep Tracker/Sleep Tracker/View/DuringSleepView/DuringSleepView.swift
> +                .foregroundColor(.AppScheme.white)
There is no way to test this view when you run the application, only in the preview. This view is only part of another view.

2023-05-16 17:38 UTC, dersim-davaod approved these changes
LGTM

2023-05-16 20:09 UTC, merged