Create `RoundedRectangleView`
ios-course/swiftcowboys-team-project pull request #55
Opened 2023-05-16 08:54 UTC by marinkman

## What?
- Created `ReusableViews` folder
- Created `RoundedRectangleView` struct

## Why?
- To close #22 

## Anything Else?
Code will be refactored after [issue#54](https://github.com/ios-course/swiftcowboys-team-project/issues/54) is completed.

2023-05-16 12:25 UTC, dersim-davaod requested changes
Consider improvements:

2023-05-16 12:25 UTC, dersim-davaod commented on Sleep Tracker/Sleep Tracker/View/SleepButton.swift
> +        })
Can you simplify the implementation and make it more flexible?

Your values of the frame means the width of the button will be the same on a different screens (iPhones). Is that what you wanted?

Something like that:
```suggestion
        Button(action: {
            changeButtonText(to: newButtonText)
        }, label: {
            Text(buttonText)
                .foregroundColor(.AppScheme.white)
                .font(.system(size: 20, weight: .bold))
                .frame(maxWidth: .infinity)
                .padding()

        })
        .background(Color.AppScheme.brightBlue)
        .cornerRadius(46)
        .padding(24)
```
?

2023-05-16 12:25 UTC, dersim-davaod commented on Sleep Tracker/Sleep Tracker/View/SleepButton.swift
> +    /// A string value that contains the text on the button. Empty string by default.
Why the button contains empty text by default?

2023-05-16 17:29 UTC, marinkman commented on Sleep Tracker/Sleep Tracker/View/SleepButton.swift
> +/// A view that displays a button to control sleep.
When pressed, the user falls asleep or wakes up.

2023-05-16 17:43 UTC, marinkman commented on Sleep Tracker/Sleep Tracker/View/SleepButton.swift
> +    @State var newButtonText = String()
I want the text on the button to change when the button is tapped.

2023-05-16 17:49 UTC, marinkman commented on Sleep Tracker/Sleep Tracker/View/SleepButton.swift
> +    /// A string value that contains the text on the button. Empty string by default.
So that we can set the text that will be displayed on the button.

2023-05-16 17:52 UTC, marinkman commented on Sleep Tracker/Sleep Tracker/View/SleepButton.swift
> +        })
No, that's not what I wanted.

2023-05-16 18:48 UTC, dersim-davaod commented on Sleep Tracker/Sleep Tracker/View/SleepButton.swift
> +    @State var newButtonText = String()
So the state of the button is a one string of text it is currently displaying.

You change the state upon specific triggers. That's it.

Does that make sense?

2023-05-16 20:20 UTC, MikhailKosarev commented on Sleep Tracker/Sleep Tracker/View/SleepButton.swift
> +/// A view that displays a button to control sleep.
So I looked in Figma and noticed that we use this button on many screens. It's not just a "sleep button", it's something more :) like a general application button.
@marinkman what do you think about it?

2023-05-16 20:25 UTC, marinkman commented on Sleep Tracker/Sleep Tracker/View/SleepButton.swift
> +/// A view that displays a button to control sleep.
@MikhailKosarev Yes, I think the button name needs to be changed.

2023-05-16 20:29 UTC, MikhailKosarev commented on Sleep Tracker/Sleep Tracker/View/SleepButton.swift
> +    @State var newButtonText = String()
I think Dersim meant that `button` just should be able to change its text which it gets outside (exactly from ViewModel). For this, it should have only one property for the current text.
And the next point is that it should not change the text inside. It should trigger its ViewModel, and the ViewModel should decide what to do next.
@dersim-davaod correct me if I'm wrong

2023-05-16 20:30 UTC, MikhailKosarev commented on Sleep Tracker/Sleep Tracker/View/SleepButton.swift
> +    @State var shouldChangeButtonText = false
I agree about naming, but do we have to store this state in the button?

2023-05-16 20:32 UTC, MikhailKosarev commented on Sleep Tracker/Sleep Tracker/View/SleepButton.swift
> +    // MARK: - Public interface
@dersim-davaod why not? We have access to these properties from the outside

2023-05-16 20:45 UTC, MikhailKosarev requested changes
Great job! The button looks the way it should.
Just simplify the logic inside the button and do a little refactoring.

2023-05-16 20:45 UTC, MikhailKosarev commented on Sleep Tracker/Sleep Tracker/View/SleepButton.swift
> +    /// A string value that contains the text on the button. Empty string by default.
Can we simplify the description? I think it's obvious, that it's a String.
```suggestion
    /// A text on the button. Empty string by default.
```
Please review the rest of doc comments.

2023-05-16 20:56 UTC, marinkman commented on Sleep Tracker/Sleep Tracker/View/SleepButton.swift
> +struct SleepButton: View {
Yes, fixed.

2023-05-16 20:57 UTC, dersim-davaod commented on Sleep Tracker/Sleep Tracker/View/SleepButton.swift
> +    @State var newButtonText = String()
Currently my question was why we use two states to show text in the button? Why we can't use only one state?

2023-05-16 20:57 UTC, marinkman commented on Sleep Tracker/Sleep Tracker/View/SleepButton.swift
> +    @State var newButtonText = String()
Fixed.

2023-05-16 20:58 UTC, dersim-davaod commented on Sleep Tracker/Sleep Tracker/View/SleepButton.swift
> +    // MARK: - Public interface
Because this is not a public interface :) 
@MikhailKosarev do you remember the difference between public and internal interface?

2023-05-16 20:59 UTC, marinkman commented on Sleep Tracker/Sleep Tracker/View/SleepButton.swift
> +    @State var shouldChangeButtonText = false
Property has been removed.

2023-05-16 21:00 UTC, marinkman commented on Sleep Tracker/Sleep Tracker/View/SleepButton.swift
> +    /// A Boolean value that indicates whether the text on the button should change after it is tapped.
Property has been removed.

2023-05-16 21:00 UTC, marinkman commented on Sleep Tracker/Sleep Tracker/View/SleepButton.swift
> +        })
Fixed.

2023-05-16 21:01 UTC, dersim-davaod commented on Sleep Tracker/Sleep Tracker/View/SleepButton.swift
> +    /// A string value that contains the text on the button. Empty string by default.
So the button can show the empty text, can't it?

Because of
> A string value that contains the text on the button

and 

> Empty string by default.

2023-05-16 21:01 UTC, marinkman commented on Sleep Tracker/Sleep Tracker/View/SleepButton.swift
> +    /// A string value that contains the text on the button. Empty string by default.
Fixed.

2023-05-16 21:03 UTC, marinkman commented on Sleep Tracker/Sleep Tracker/View/SleepButton.swift
> +    /// A string value that contains the text on the button. Empty string by default.
Fixed.

2023-05-16 21:23 UTC, dersim-davaod requested changes
Please resolve the conflicts.

2023-05-16 21:39 UTC, MikhailKosarev commented on Sleep Tracker/Sleep Tracker/View/SleepButton.swift
> +    // MARK: - Public interface
of course :) in Swift's terms of access control, you're right. :)

2023-05-17 07:36 UTC, dersim-davaod approved these changes
LGTM

2023-05-17 07:39 UTC, meschya approved these changes
LGTM

2023-05-17 09:02 UTC, MikhailKosarev approved these changes
LGTM

2023-05-17 09:15 UTC, merged