Implementing `LocalStorage`
ios-course/swiftcowboys-team-project pull request #60
Opened 2023-05-16 21:33 UTC by MikhailKosarev

## What?
- Implemented `LocalStorage` class as a wrapper to have a convenient interface to the local storage.

## Why?
- to close #53 

## Testing?
The public interface is covered with tests. let me know if I missed some test cases.

## Anything else?
Right now it matches the max size of the PR and it seems logical not to divide it into multiple PRs. Let me know if I'm wrong and if it's hard for you to review. Also, if any code needs to be added after the change requests - maybe I'll split it up.

2023-05-17 08:01 UTC, dersim-davaod requested changes
Good job!
Consider some improvements:

2023-05-17 08:01 UTC, dersim-davaod commented on Sleep Tracker/Sleep Tracker/Model/LocalStorage.swift
> +    private let defaults = UserDefaults.standard
What does that mean "a standard UserDefaults"?

2023-05-17 09:14 UTC, marinkman reviewed
You need to resolve the conflict.

2023-05-17 18:45 UTC, MikhailKosarev commented on Sleep Tracker/Sleep Tracker/Model/LocalStorage.swift
> +/// A wrapper that provides a convenient interface to interact with local storage using `UserDefaults`.
you're right, fixed

2023-05-17 18:46 UTC, MikhailKosarev commented on Sleep Tracker/Sleep Tracker/Model/LocalStorage.swift
> +    /// Sets the given value for the given key in local storage.
thanks, fixed

2023-05-17 18:55 UTC, MikhailKosarev commented on Sleep Tracker/Sleep Tracker/Model/LocalStorage.swift
> +    /// or the value has a different type.
Improved the documentation. let me know if it's still unclear.

2023-05-17 18:58 UTC, MikhailKosarev commented on Sleep Tracker/Sleep Tracker/Model/LocalStorage.swift
> +    /// Deletes the value associated with the given key from local storage.
improved the documentation

2023-05-17 19:05 UTC, MikhailKosarev commented on Sleep Tracker/Sleep TrackerTests/Model/LocalStorage/DeleteTests.swift
> +        let retrievedValue: Int? = storage.get(forKey: key)
Yeah, otherwise we need to cast the retrieved value. I think now it's not a problem for us, in the future, we can improve the functionality of the class.

2023-05-17 19:08 UTC, MikhailKosarev commented on Sleep Tracker/Sleep Tracker/Model/LocalStorage.swift
> +    func set<T>(_ value: T, forKey key: String) {
yes, added to the documentation

2023-05-17 20:16 UTC, MikhailKosarev commented on Sleep Tracker/Sleep Tracker/Model/LocalStorage.swift
> +    private let defaults = UserDefaults.standard
It's the shared defaults object. Do you think it's better to create a separate one?

2023-05-17 20:17 UTC, MikhailKosarev commented on Sleep Tracker/Sleep Tracker/Model/LocalStorage.swift
> +    private let defaults = UserDefaults.standard
fixed

2023-05-17 20:18 UTC, MikhailKosarev commented on Sleep Tracker/Sleep TrackerTests/Model/LocalStorage/DeleteTests.swift
> +final class DeleteTests: XCTestCase {
You're right, thanks. Fixed

2023-05-17 20:18 UTC, MikhailKosarev commented on Sleep Tracker/Sleep TrackerTests/Model/LocalStorage/DeleteTests.swift
> +        // the code compiles
fixed

2023-05-17 20:20 UTC, MikhailKosarev commented on Sleep Tracker/Sleep TrackerTests/Model/LocalStorage/DeleteTests.swift
> +        storage.set("Value 1", forKey: "key1")
agree, fixed

2023-05-17 20:20 UTC, MikhailKosarev commented on Sleep Tracker/Sleep TrackerTests/Model/LocalStorage/DeleteTests.swift
> +    func testDeleteRemovesCorrespondingValuesWhenDeletesForAFewKeys() {
thanks, fixed

2023-05-17 20:21 UTC, MikhailKosarev commented on Sleep Tracker/Sleep TrackerTests/Model/LocalStorage/DeleteTests.swift
> +        let value1: String? = storage.get(forKey: "key1")
ok, fixed

2023-05-17 20:22 UTC, MikhailKosarev commented on Sleep Tracker/Sleep TrackerTests/Model/LocalStorage/DeleteTests.swift
> +        let numberToSet = 100
agree, thanks

2023-05-17 20:29 UTC, MikhailKosarev commented on Sleep Tracker/Sleep TrackerTests/Model/LocalStorage/DeleteTests.swift
> +        let nonExistentKey = "nonExistentKey"
thanks, fixed

2023-05-17 20:29 UTC, MikhailKosarev commented on Sleep Tracker/Sleep TrackerTests/Model/LocalStorage/DeleteTests.swift
> +    func testDeleteRemovesValueForExistingkey() {
Thanks, fixed

2023-05-17 20:32 UTC, MikhailKosarev commented on Sleep Tracker/Sleep Tracker/Model/LocalStorage.swift
> +        return defaults.object(forKey: key) as? T
of course, thanks. Fixed

2023-05-17 21:32 UTC, dersim-davaod commented on Sleep Tracker/Sleep Tracker/Model/LocalStorage.swift
> +    private let defaults = UserDefaults.standard
Who can share the storage? Say, can the other app update some key?

2023-05-18 19:46 UTC, dersim-davaod commented on Sleep Tracker/Sleep TrackerTests/Model/LocalStorage/DeleteTests.swift
> +final class LocalStorageDeleteTests: XCTestCase {
The name of the file doesn't match the type.

2023-05-18 19:46 UTC, dersim-davaod commented on Sleep Tracker/Sleep TrackerTests/Model/LocalStorage/GetTests.swift
> +final class LocalStorageGetTests: XCTestCase {
The name of the file doesn't match the type.

2023-05-18 19:46 UTC, dersim-davaod commented on Sleep Tracker/Sleep TrackerTests/Model/LocalStorage/SetTests.swift
> +final class LocalStorageSetTests: XCTestCase {
The name of the file doesn't match the type.

2023-05-18 19:53 UTC, dersim-davaod commented on Sleep Tracker/Sleep TrackerTests/Model/LocalStorage/DeleteTests.swift
> +        let nonExistentKey = "nonExistentKey"
BTW, alternatively you can remove the key from the storage in the `// given section` to make sure there's no specific key within the `// when` section.

2023-05-18 19:53 UTC, dersim-davaod commented on Sleep Tracker/Sleep TrackerTests/Model/LocalStorage/DeleteTests.swift
> +        let retrievedValue: Int? = storage.get(forKey: key)
This is unacceptable.
Could you please improve the API as it was discussed?

2023-05-18 19:54 UTC, dersim-davaod commented on Sleep Tracker/Sleep Tracker/Model/LocalStorage.swift
> +    /// or the value has a different type.
Unfortunately, it is still unclear.
Specifically, take a look at:

> or the value has a type different from the specified one.

Where I should specify type?

2023-05-19 16:29 UTC, MikhailKosarev commented on Sleep Tracker/Sleep Tracker/Model/LocalStorage.swift
> +    private let defaults = UserDefaults.standard
No, just inside the app. It's shared through the app, every object can use the sam one instance of the storage

2023-05-31 07:36 UTC, closed without merging

2023-05-31 07:37 UTC, MikhailKosarev commented
The PR was closed, as the issue is not actual at the moment.