Create `AppFont` and `AppUIConstant` enum
ios-course/swiftcowboys-team-project pull request #65
Opened 2023-05-19 18:49 UTC by marinkman

## What?
- Created `AppFont` enum 
- Created `AppUIConstant` enum
- Created `AppFontTests` class to tests `AppFont` enum
- Created `AppUIConstantTests` class to tests `AppUIConstant` enum

## Why?
- Part of the #54

2023-05-22 21:09 UTC, MikhailKosarev requested changes
Well done!
Some minor improvements and questions:

2023-05-22 21:09 UTC, MikhailKosarev commented on Sleep Tracker/SleepTracker/Helpers/AppFont.swift
> +/// The font used in the application.
It's more about the size. Would it be better to name it like this?
```suggestion
/// The font size used in the application.
```

2023-05-22 21:09 UTC, MikhailKosarev commented on Sleep Tracker/SleepTracker/Helpers/AppFont.swift
> +enum AppFont {
The same as above
```suggestion
enum AppFontSize {
```

2023-05-22 21:09 UTC, MikhailKosarev commented on Sleep Tracker/SleepTracker/Helpers/AppUIConstant.swift
> +/// The size of the UI element used in the application.
According to the opacity, there are not only sizes here. Would it be better this way?
```suggestion
/// The settings of the UI element used in the application.
```

2023-05-22 21:09 UTC, MikhailKosarev commented on Sleep Tracker/SleepTrackerUITests/Helpers/AppUIConstantTests.swift
> +    func testAppUIConstantSizesReturnCorrectValues() {
nit:
```suggestion
    func testAppUIConstantSizesReturnsCorrectValues() {
```

2023-05-22 21:09 UTC, MikhailKosarev commented on Sleep Tracker/SleepTrackerUITests/Helpers/AppFontTests.swift
> +    func testAppFontSizesReturnCorrectValues() {
nit:
```suggestion
    func testAppFontSizesReturnsCorrectValues() {
```

2023-05-23 16:49 UTC, dersim-davaod reviewed
Please improve the implementation as we have discussed.
Do not forget what is the "magic number" is.

2023-05-26 09:37 UTC, marinkman commented on Sleep Tracker/SleepTracker/Helpers/AppFont.swift
> +/// The font used in the application.
Yes. Fixed.

2023-05-26 09:37 UTC, marinkman commented on Sleep Tracker/SleepTracker/Helpers/AppFont.swift
> +enum AppFont {
Fixed.

2023-05-26 09:38 UTC, marinkman commented on Sleep Tracker/SleepTracker/Helpers/AppUIConstant.swift
> +/// The size of the UI element used in the application.
Yes. Fixed.

2023-05-26 09:38 UTC, marinkman commented on Sleep Tracker/SleepTrackerUITests/Helpers/AppUIConstantTests.swift
> +    func testAppUIConstantSizesReturnCorrectValues() {
Fixed.

2023-05-26 09:38 UTC, marinkman commented on Sleep Tracker/SleepTrackerUITests/Helpers/AppFontTests.swift
> +    func testAppFontSizesReturnCorrectValues() {
Fixed.

2023-05-30 16:07 UTC, meschya approved these changes
LGTM

2023-05-31 08:43 UTC, dersim-davaod reviewed
Consider minor improvements:

2023-05-31 08:43 UTC, dersim-davaod commented on Sleep Tracker/SleepTracker/Helpers/AppUIConstant.swift
> +    static let translucent: Double = 0.5
nit:
```suggestion
    static let semitransparent: Double = 0.5
```

2023-05-31 08:43 UTC, dersim-davaod commented on Sleep Tracker/SleepTracker/Helpers/AppUIConstant.swift
> +    static let maxFrameHeight: CGFloat = 100
So I can't have any frame in the app which is more than 100 points?

That's confusing.

2023-05-31 08:43 UTC, dersim-davaod commented on Sleep Tracker/SleepTracker/Helpers/AppFontSize.swift
> +}
nit:

```suggestion
extension CGFloat {
    enum AppFontSize {
        /// A font size used for small details.
        static let detail: CGFloat = 12
        /// A base font size.
        static let base: CGFloat = 20
        /// A font size used for headings.
        static let heading: CGFloat = 40
    }
}
```

?

2023-05-31 08:43 UTC, dersim-davaod commented on Sleep Tracker/SleepTracker/Helpers/AppFontSize.swift
> +    /// A base font size.
```suggestion
    /// A base font size <used for what?>.
```

2023-05-31 08:43 UTC, dersim-davaod commented on Sleep Tracker/SleepTracker/Helpers/AppFontSize.swift
> +    /// A font size used for small details.
nit:

"Yesterday was a sunny weather"

Is that a small detail? ;)
What is a "small details"?

2023-05-31 08:43 UTC, dersim-davaod commented on Sleep Tracker/SleepTracker/Helpers/AppUIConstant.swift
> +    static let tabBarCornerRadius: CGFloat = 50
nit:

Could you please remind me: do we make rounded corners for a tab bar itself? Or only for its elements (items)?

2023-06-02 12:44 UTC, marinkman commented on Sleep Tracker/SleepTracker/Helpers/AppUIConstant.swift
> +    static let translucent: Double = 0.5
Fixed.

2023-06-02 12:45 UTC, marinkman commented on Sleep Tracker/SleepTracker/Helpers/AppUIConstant.swift
> +    static let maxFrameHeight: CGFloat = 100
Corrected name and documentation.

2023-06-02 12:45 UTC, marinkman commented on Sleep Tracker/SleepTracker/Helpers/AppFontSize.swift
> +}
Done.

2023-06-02 12:46 UTC, marinkman commented on Sleep Tracker/SleepTracker/Helpers/AppFontSize.swift
> +    /// A base font size.
Corrected documentation.

2023-06-02 12:46 UTC, marinkman commented on Sleep Tracker/SleepTracker/Helpers/AppFontSize.swift
> +    /// A font size used for small details.
Corrected name and documentation.

2023-06-02 12:47 UTC, marinkman commented on Sleep Tracker/SleepTracker/Helpers/AppUIConstant.swift
> +    static let tabBarCornerRadius: CGFloat = 50
For the tab bar itself.

2023-06-02 13:47 UTC, dersim-davaod commented on Sleep Tracker/SleepTrackerTests/Helpers/AppUIConstantTests.swift
> +        XCTAssertEqual(maxFrameHeightInAlarmSetup, AppUIConstant.maxFrameHeightInAlarmSetup)
As we use the expected values only once during the test, can we make it simple and easier to read:

```suggestion
        XCTAssertEqual(AppUIConstant.baseCornerRadius, 10)
        XCTAssertEqual(AppUIConstant.alarmCornerRadius, 20)
        XCTAssertEqual(AppUIConstant.tabBarCornerRadius, 50)
        XCTAssertEqual(AppUIConstant.largeCornerRadius, 80)

        XCTAssertEqual(AppUIConstant.transparent, 0.0)
        XCTAssertEqual(AppUIConstant.semitransparent, 0,5)
        XCTAssertEqual(AppUIConstant.opaque, 1.0)

        XCTAssertEqual(AppUIConstant.minFrameWidthInAlarmSetup, 0)
        XCTAssertEqual(AppUIConstant.maxFrameHeightInAlarmSetup, 100)
```

?

2023-06-02 13:47 UTC, dersim-davaod commented on Sleep Tracker/SleepTracker/Helpers/AppUIConstant.swift
> +    static let maxFrameHeight: CGFloat = 100
Now I have one more question: if the constant makes sense only within the `AlarmView`, why it is available internally for all other types?

2023-06-02 13:49 UTC, dersim-davaod requested changes
Do we want to apply these constants in the current PR?
I'd expect to use these types immediately, so right after the merge of the current PR everyone avoids magic numbers. WDYT?

2023-06-02 13:50 UTC, dersim-davaod commented on Sleep Tracker/SleepTracker/Helpers/AppFontSize.swift
> +    /// A font size used for small details.
What is "a small text" now?
Is that a text on iPhone SE? Or the text that contains less than 3 lines?  ;)

2023-06-05 13:25 UTC, marinkman commented on Sleep Tracker/SleepTrackerTests/Helpers/AppUIConstantTests.swift
> +        XCTAssertEqual(maxFrameHeightInAlarmSetup, AppUIConstant.maxFrameHeightInAlarmSetup)
Yes, done

2023-06-05 13:33 UTC, marinkman commented on Sleep Tracker/SleepTracker/Helpers/AppUIConstant.swift
> +    static let maxFrameHeight: CGFloat = 100
You are right. This should not be. 
I removed these constants.

2023-06-05 13:44 UTC, marinkman commented
> Do we want to apply these constants in the current PR?
> I'd expect to use these types immediately, so right after the merge of the current PR everyone avoids magic numbers. WDYT?

After merging this PR, everyone will have to avoid magic numbers. 
However, already existing magic numbers will be replaced in [this issue](https://github.com/ios-course/swiftcowboys-team-project/issues/56).

2023-06-05 20:03 UTC, dersim-davaod approved these changes
LGTM

2023-06-05 20:03 UTC, dersim-davaod commented on SleepTracker/SleepTracker/Helpers/CGFloat+AppFontSize.swift
> +        /// A font size used for caption.
nit:
```suggestion
        /// A font size used for captions.
```

to be consistent with the rest of doc comments.

2023-06-05 20:03 UTC, dersim-davaod commented on SleepTracker/SleepTrackerTests/Helpers/CGFloat+AppFontSizeTests.swift
> +        XCTAssertEqual(heading, .AppFontSize.heading)
nit:

```suggestion
        XCTAssertEqual(.AppFontSize.caption, 12)
        XCTAssertEqual(.AppFontSize.base, 20)
        XCTAssertEqual( .AppFontSize.heading, 40)
        
```
to be consistent with the `AppUIConstantTests`?

2023-06-05 20:53 UTC, MikhailKosarev approved these changes
LGTM

2023-06-06 07:56 UTC, marinkman commented on SleepTracker/SleepTracker/Helpers/CGFloat+AppFontSize.swift
> +        /// A font size used for caption.
Fixed.

2023-06-06 11:41 UTC, MikhailKosarev commented
@marinkman just pointing out that there are unresolved conflicts in this PR :)

2023-06-06 11:50 UTC, marinkman commented
> @marinkman just pointing out that there are unresolved conflicts in this PR :)

@MikhailKosarev what conflicts are you talking about?

2023-06-06 12:01 UTC, MikhailKosarev commented
@marinkman Strangely, I saw conflicts when merging. And now there are none.

2023-06-06 14:02 UTC, dersim-davaod approved these changes
LGTM

2023-06-06 14:14 UTC, marinkman commented
Resolved the conflict in the `CHANGELOG.md` file.

2023-06-06 14:16 UTC, MikhailKosarev approved these changes
LGTM

2023-06-06 14:38 UTC, meschya approved these changes
LGTM

2023-06-06 14:39 UTC, merged