Filling the `CHANGELOG.md` file
ios-course/swiftcowboys-team-project pull request #68
Opened 2023-05-22 21:00 UTC by MikhailKosarev

## What?
- Filled the `CHANGELOG.md` file with the structure according to the [keepachangelog](https://keepachangelog.com/en/1.0.0/).
- Added to the `CHANGELOG.md` all the changes made before the completion of this issue.

## Why?
To close #59

2023-05-26 09:14 UTC, marinkman reviewed
But we still don't keep a changelog and there are already new changes.

2023-05-30 20:51 UTC, MikhailKosarev commented on CHANGELOG.md
> +-  Added `Color` extension - [#37](https://github.com/ios-course/swiftcowboys-team-project/pull/37)
done

2023-05-31 07:14 UTC, marinkman reviewed
I have one question.

2023-05-31 07:14 UTC, marinkman commented on CHANGELOG.md
> +- Added extension for the `Date` - [#87](https://github.com/ios-course/swiftcowboys-team-project/pull/82)
Why is this line in the "changed" section?

2023-05-31 07:43 UTC, MikhailKosarev commented on CHANGELOG.md
> +- Added extension for the `Date` - [#87](https://github.com/ios-course/swiftcowboys-team-project/pull/82)
You're right, thanks. Moved

2023-05-31 07:46 UTC, dersim-davaod requested changes
Please double-check the changelog contains the correct intention of the changes.

2023-05-31 08:40 UTC, MikhailKosarev commented on CHANGELOG.md
> +- Removed empty `SleepTrackerTests.swift` file from the `SleepTrackerTests` target - [#82](https://github.com/ios-course/swiftcowboys-team-project/pull/82)
@dersim-davaod why is it wrong? I can't understand, can u explain, please?

2023-05-31 09:19 UTC, dersim-davaod commented on CHANGELOG.md
> +- Removed empty `SleepTrackerTests.swift` file from the `SleepTrackerTests` target - [#82](https://github.com/ios-course/swiftcowboys-team-project/pull/82)
The description in the changelog doesn't match the changes introduced in ht PR.

2023-05-31 10:55 UTC, MikhailKosarev commented on CHANGELOG.md
> +
fixed

2023-05-31 11:02 UTC, meschya requested changes

2023-05-31 11:02 UTC, meschya commented on CHANGELOG.md
> +-  Added extension `Date+ShortComponents`for the `Date` - [#87](https://github.com/ios-course/swiftcowboys-team-project/pull/82)
```suggestion
-  Added extension `Date+ShortComponents`for the `Date` - [#87](https://github.com/ios-course/swiftcowboys-team-project/pull/87)
```
Incorrect reference to PR

2023-05-31 11:04 UTC, marinkman commented on CHANGELOG.md
> +
Why is there an empty line here?

2023-05-31 11:17 UTC, MikhailKosarev commented on CHANGELOG.md
> +-  Added extension `Date+ShortComponents`for the `Date` - [#87](https://github.com/ios-course/swiftcowboys-team-project/pull/82)
thanks, fixed

2023-05-31 11:18 UTC, MikhailKosarev commented on CHANGELOG.md
> +
thanks, didn't pay attention. Fixed

2023-05-31 11:18 UTC, dersim-davaod requested changes
Consider improvements:

2023-05-31 11:18 UTC, dersim-davaod commented on CHANGELOG.md
> +-  Created `SleepPageView` with subviews: `AlarmSetupView`, `EstimatedSleepDurationLabelView`, `NoAlarmLabelView`, `RoundedAlarmView`, `WheelTimePickerView`, according to the app design - [#39](https
Did we create a `SleepPageView`?
I thought we have created `SleepSetupView` there.

2023-05-31 11:18 UTC, dersim-davaod commented on CHANGELOG.md
> +-  Created `RoundedRectangleView` according to the app design - [#55](https://github.com/ios-course/swiftcowboys-team-project/pull/55)
nit:

```suggestion
-  Created `RoundedRectangleView` to show X/to allow Y/etc - [#55](https://github.com/ios-course/swiftcowboys-team-project/pull/55)
```

I'd suggest to have something like that.

2023-05-31 11:18 UTC, dersim-davaod commented on CHANGELOG.md
> +-  Added accidentally uncommitted changes for `SleepSetupView` - [#67](https://github.com/ios-course/swiftcowboys-team-project/pull/67)
nit:

```suggestion
-  Fixed the implementation for `SleepSetupView` (commited missing changes) - [#67](https://github.com/ios-course/swiftcowboys-team-project/pull/67)
```

2023-05-31 11:18 UTC, dersim-davaod commented on CHANGELOG.md
> +-  Changed `SwiftFormat` script to support `arm64` - [#73](https://github.com/ios-course/swiftcowboys-team-project/pull/73)
nit:

```suggestion
-  Update `SwiftFormat` build phases to be able to run linters on `arm64` - [#73](https://github.com/ios-course/swiftcowboys-team-project/pull/73)
```

2023-05-31 11:18 UTC, dersim-davaod commented on CHANGELOG.md
> +-  Removed empty `SleepTrackerTests.swift` file from the `SleepTrackerTests` target. Removed the `SleepTrackerUITests` target. Unit tests from the `SleepTrackerUITests` target moved into the `SleepTr
This is not important:
 
```suggestion
Removed the `SleepTrackerUITests` target. Unit tests now live in the new `SleepTrackerTests` target. Fixed failed unit tests - [#82](https://github.com/ios-course/swiftcowboys-team-project/pull/82)
```

2023-05-31 11:18 UTC, dersim-davaod commented on CHANGELOG.md
> +-  Added an extension `UserDefaults+SharedAppPreferences` for the `UserDefaults` with tests - [#84](https://github.com/ios-course/swiftcowboys-team-project/pull/84)
```suggestion
-  Added the extension `UserDefaults+SharedAppPreferences` with unit tests - [#84](https://github.com/ios-course/swiftcowboys-team-project/pull/84)
```

2023-05-31 11:18 UTC, dersim-davaod commented on CHANGELOG.md
> +-  Added extension `Date+ShortComponents`for the `Date` - [#87](https://github.com/ios-course/swiftcowboys-team-project/pull/82)
nit:

I know from the name the extension is for the `Date` :) 

```suggestion
-  Added the `Date+ShortComponents` extension - [#87](https://github.com/ios-course/swiftcowboys-team-project/pull/82)
```

2023-05-31 11:22 UTC, MikhailKosarev commented on CHANGELOG.md
> +-  Created `SleepPageView` with subviews: `AlarmSetupView`, `EstimatedSleepDurationLabelView`, `NoAlarmLabelView`, `RoundedAlarmView`, `WheelTimePickerView`, according to the app design - [#39](https
you're right. Fixed

2023-05-31 11:23 UTC, MikhailKosarev commented on CHANGELOG.md
> +-  Added accidentally uncommitted changes for `SleepSetupView` - [#67](https://github.com/ios-course/swiftcowboys-team-project/pull/67)
thanks, you're right. Changed

2023-05-31 11:23 UTC, MikhailKosarev commented on CHANGELOG.md
> +-  Changed `SwiftFormat` script to support `arm64` - [#73](https://github.com/ios-course/swiftcowboys-team-project/pull/73)
thanks, changed

2023-05-31 11:24 UTC, MikhailKosarev commented on CHANGELOG.md
> +-  Removed empty `SleepTrackerTests.swift` file from the `SleepTrackerTests` target. Removed the `SleepTrackerUITests` target. Unit tests from the `SleepTrackerUITests` target moved into the `SleepTr
fixed

2023-05-31 11:25 UTC, MikhailKosarev commented on CHANGELOG.md
> +-  Added extension `Date+ShortComponents`for the `Date` - [#87](https://github.com/ios-course/swiftcowboys-team-project/pull/82)
yeah, you're right :)

2023-05-31 11:26 UTC, MikhailKosarev commented on CHANGELOG.md
> +-  Added an extension `UserDefaults+SharedAppPreferences` for the `UserDefaults` with tests - [#84](https://github.com/ios-course/swiftcowboys-team-project/pull/84)
fixed

2023-05-31 11:31 UTC, MikhailKosarev commented on CHANGELOG.md
> +-  Created `RoundedRectangleView` according to the app design - [#55](https://github.com/ios-course/swiftcowboys-team-project/pull/55)
I think in this lin there is no sense at all to write it. But I double-checked the rest of the lines. Thanks

2023-05-31 11:37 UTC, dersim-davaod commented on CHANGELOG.md
> +-  Created `RoundedRectangleView` according to the app design - [#55](https://github.com/ios-course/swiftcowboys-team-project/pull/55)
It's up to you, but then it will be much easier to write release notes.

2023-05-31 11:38 UTC, dersim-davaod approved these changes
LGTM

2023-05-31 11:40 UTC, marinkman approved these changes
LGTM

2023-05-31 11:42 UTC, meschya approved these changes
LGTM

2023-05-31 11:43 UTC, merged