Update the `README.md` file
ios-course/swiftcowboys-team-project pull request #86
Opened 2023-05-30 11:52 UTC by marinkman

## What?
- Added `Dev environment` section and filled with information.
- Added `Installation` section and filled with information.

## Why?
- To close #83  

## Anything Else?
- Removed space from project name in file.
- Removed Nik Gribok - [@nek-to](https://github.com/nek-to) from the authors section.

2023-05-30 12:38 UTC, MikhailKosarev reviewed
Have some questions:

2023-05-30 12:38 UTC, MikhailKosarev commented on README.md
> +![macOS](https://img.shields.io/badge/macOS-13.3.1%2B-311B6B)
Should we provide `13.3.1+` instead of just `13.3.1`, which we have frozen?  It may not work in the next version.

2023-05-30 12:38 UTC, MikhailKosarev commented on README.md
> +![SDKs_for_iOS](https://img.shields.io/badge/SDKs%20for%20iOS-16.0%2B-F3FF91)
the same as above

2023-05-30 12:47 UTC, marinkman commented on README.md
> -Nik Gribok - [@nek-to](https://github.com/nek-to)
Yes, he did something before in the current repository, but now he has no rights. 
We need to know what is usually done in such situations.

2023-05-30 13:04 UTC, marinkman commented on README.md
> +
I think that something like this can be written at the top of the "installation" section, and not here.

2023-05-30 13:07 UTC, marinkman commented on README.md
> +7. Select a device as the destination to run the project. See the [documentation](https://developer.apple.com/documentation/xcode/running-your-app-in-simulator-or-on-a-device) for more details on run
Yes, sure.

2023-05-30 15:38 UTC, marinkman commented on README.md
> +![macOS](https://img.shields.io/badge/macOS-13.3.1%2B-311B6B)
Changed to 13.3.1.

2023-05-30 15:39 UTC, marinkman commented on README.md
> +![SDKs_for_iOS](https://img.shields.io/badge/SDKs%20for%20iOS-16.0%2B-F3FF91)
Changed to 16.0.

2023-05-30 15:55 UTC, dersim-davaod commented on README.md
> -Nik Gribok - [@nek-to](https://github.com/nek-to)
Keep the list of active contributors only.
Please do NOT include me in the list.

2023-05-31 07:55 UTC, dersim-davaod requested changes
Please make sure the instruction steps can be reproduced easily.

2023-05-31 09:19 UTC, marinkman commented on README.md
> +1. Go to the [Releases](https://github.com/ios-course/swiftcowboys-team-project/releases) section in the current repository.
They can make a test release.

2023-05-31 09:59 UTC, dersim-davaod commented on README.md
> +![macOS](https://img.shields.io/badge/macOS-13.3.1-311B6B)
> Yes you can.

How can I know that?

Why you haven't guarantee the work with later versions?

2023-05-31 09:59 UTC, dersim-davaod commented on README.md
> +![SDKs_for_iOS](https://img.shields.io/badge/SDKs%20for%20iOS-16.0-F3FF91)
Why you can't guarantee the work for all versions above the deployment target?

2023-05-31 10:49 UTC, marinkman commented on README.md
> +![macOS](https://img.shields.io/badge/macOS-13.3.1-311B6B)
> How can I know that?
This is indicated in the installation section.

> Why you haven't guarantee the work with later versions?
Because we don't know what changes will be in later versions.

2023-05-31 10:55 UTC, marinkman commented on README.md
> +![SDKs_for_iOS](https://img.shields.io/badge/SDKs%20for%20iOS-16.0-F3FF91)
Because we don't know what changes will be in later versions.
Some APIs may become unavailable/obsolete.

2023-05-31 11:34 UTC, marinkman commented on README.md
> +1. Go to the [Releases](https://github.com/ios-course/swiftcowboys-team-project/releases) section in the current repository.
[Test release](https://github.com/ios-course/swiftcowboys-team-project/releases/tag/test)

2023-05-31 14:14 UTC, MikhailKosarev requested changes
I tried all the steps and ran into some questions/problems:

2023-05-31 14:14 UTC, MikhailKosarev commented on README.md
> +- You need to have the environment in the versions specified in the [Dev environment](#dev-environment). You can run the application in a different environment, but we don't guarantee it will work.
nit: maybe this way it will look better?
```suggestion
Note: You need to have the environment in the versions specified in the [Dev environment](#dev-environment). You can run the application in a different environment, but we don't guarantee it will work.
```

2023-05-31 14:14 UTC, MikhailKosarev commented on README.md
> +5. Go to the directory with the extracted project.
I tried and didn't find the `SleepTracker.xcodeproj` file in the extracted directory.
```suggestion
5. Go to the directory with the extracted project and then in folder `Sleep Tracker`.
```

2023-05-31 14:14 UTC, MikhailKosarev commented on README.md
> +6. Find the file `SleepTracker.xcodeproj` and open it.
I think it makes sense to write the program to open in :)
```suggestion
6. Find the file `SleepTracker.xcodeproj` and open it in `Xcode`.
```

2023-05-31 14:14 UTC, MikhailKosarev commented on README.md
> +6. Find the file `SleepTracker.xcodeproj` and open it.
Do we need to give instructions on what to do with this window?
<img width="267" alt="image" src="https://github.com/ios-course/swiftcowboys-team-project/assets/100238123/a229b488-dc48-4522-990a-db7be2e2ed7b">

2023-05-31 14:14 UTC, MikhailKosarev commented on README.md
> +7. Select a device as the destination to run the project. See the [documentation](https://developer.apple.com/documentation/xcode/running-your-app-in-simulator-or-on-a-device) for more details on run
I have a problem with running on the device. We'll have to think about that.

2023-05-31 16:17 UTC, marinkman commented on README.md
> +5. Go to the directory with the extracted project.
Done.

2023-05-31 16:18 UTC, marinkman commented on README.md
> +6. Find the file `SleepTracker.xcodeproj` and open it.
Done.

2023-05-31 17:27 UTC, marinkman commented on README.md
> +7. Select a device as the destination to run the project. See the [documentation](https://developer.apple.com/documentation/xcode/running-your-app-in-simulator-or-on-a-device) for more details on run
I don't understand what the problem is.

2023-05-31 17:34 UTC, marinkman commented on README.md
> +6. Find the file `SleepTracker.xcodeproj` and open it.
Added.

2023-05-31 20:59 UTC, MikhailKosarev commented on README.md
> +7. Select a device as the destination to run the project. See the [documentation](https://developer.apple.com/documentation/xcode/running-your-app-in-simulator-or-on-a-device) for more details on run
discussed it at the meeting. Solved

2023-05-31 21:00 UTC, MikhailKosarev approved these changes
LGTM

2023-06-01 06:27 UTC, dersim-davaod reviewed
Please consider minor improvements:

2023-06-01 06:27 UTC, dersim-davaod commented on README.md
> +1. Click "Trust and Open" in the pop-up window to open the file.
nit:

not everyone has such pop-up, it depends on a user's security settings.

```suggestion
1. If the following pop-up appears...
```

2023-06-01 06:27 UTC, dersim-davaod commented on README.md
> +8. Click the run button.
nit:

```suggestion
8. Click the `Run` button and wait until the app is installed and launched.
```

2023-06-01 06:27 UTC, dersim-davaod commented on README.md
> +1. Find the file `SleepTracker.xcodeproj` and open it in `Xcode`.
nit:

```suggestion
1. Open the `Sleep Tracker/SleepTracker.xcodeproj` file using the `Xcode`.
```

2023-06-01 07:10 UTC, MikhailKosarev requested changes
Overall LGTM. Please add changes to the `CHANGELOG.md`

2023-06-01 08:44 UTC, marinkman commented on README.md
> +1. Click "Trust and Open" in the pop-up window to open the file.
Fixed.

2023-06-01 08:44 UTC, marinkman commented on README.md
> +8. Click the run button.
Fixed.

2023-06-01 08:45 UTC, marinkman commented on README.md
> +1. Find the file `SleepTracker.xcodeproj` and open it in `Xcode`.
Done.

2023-06-01 08:54 UTC, dersim-davaod commented on CHANGELOG.md
> +-  Added "Dev environment" and "Installation" sections to the `README.md` file. Removed space from project name in the `README.md` file. Removed Nik Gribok - [@nek-to](https://github.com/nek-to) from
I suggest to keep `Images` dir into the `Docs` dir so it's easy to understand the images are not part of the application (assets).

2023-06-01 08:54 UTC, dersim-davaod commented on README.md
> +   ![warning](./Images/Warning_when_opening_a_project.png)
You can use `<img>` tag to scale the image in markdown, otherwise it's too large.

2023-06-01 09:17 UTC, MikhailKosarev reviewed
I have no comments other than what Dersim wrote. Please send it back for review after they are fixed.

2023-06-01 09:50 UTC, marinkman commented on CHANGELOG.md
> +-  Added "Dev environment" and "Installation" sections to the `README.md` file. Removed space from project name in the `README.md` file. Removed Nik Gribok - [@nek-to](https://github.com/nek-to) from
Done.

2023-06-01 09:50 UTC, marinkman commented on CHANGELOG.md
> +-  Added "Dev environment" and "Installation" sections to the `README.md` file. Removed space from project name in the `README.md` file. Removed Nik Gribok - [@nek-to](https://github.com/nek-to) from
Done.

2023-06-01 09:50 UTC, marinkman commented on README.md
> +   ![warning](./Images/Warning_when_opening_a_project.png)
Done.

2023-06-01 10:19 UTC, MikhailKosarev approved these changes
LGTM

2023-06-01 10:40 UTC, dersim-davaod approved these changes
LGTM

2023-06-01 10:52 UTC, merged