Implement the `SleepPageView` and corresponding logic
ios-course/swiftcowboys-team-project pull request #88
Opened 2023-05-30 19:30 UTC by dersim-davaod

Resolves #45

2023-05-30 21:24 UTC, MikhailKosarev requested changes
have some questions:

2023-05-30 21:24 UTC, MikhailKosarev commented on Sleep Tracker/SleepTracker/ViewModel/SleepPageViewModel.swift
> +final class SleepPageViewModel: ObservableObject {
should we add documentation for the class?

2023-05-30 21:24 UTC, MikhailKosarev commented on Sleep Tracker/SleepTracker/ViewModel/SleepPageViewModel.swift
> +            ? "\(estimatedSleepTimePrefixText):" +
a little hard to read. Maybe smth like this:
```suggestion
            ? "\(estimatedSleepTimePrefixText):" + "\n" +
            "\(hours)h" + " " + "\(minutes)m"
            : estimatedSleepTimeNotAvailableText
```
?

2023-05-31 06:39 UTC, dersim-davaod commented on Sleep Tracker/SleepTracker/ViewModel/SleepPageViewModel.swift
> +            ? "\(estimatedSleepTimePrefixText):" +
Yeah, the linter breaks "beautiful" formatting.
I've updated it, please check it out.

2023-05-31 06:39 UTC, dersim-davaod commented on Sleep Tracker/SleepTracker/ViewModel/SleepPageViewModel.swift
> +final class SleepPageViewModel: ObservableObject {
Sure, updated!

2023-05-31 06:39 UTC, dersim-davaod commented on Sleep Tracker/SleepTracker/View/SleepPageView/DuringSleepView/DuringSleepView.swift
> +    /// Text to show whether the alarm on/off. If the alarm. If the alarm is off,
Fixed.

2023-05-31 07:55 UTC, marinkman reviewed
Generally good, but `Predicted sleep duration` should be from 0m to 23h 59m.
It should be 0m at the current time, not 24h 0m.

2023-05-31 11:03 UTC, MikhailKosarev requested changes
Overall, it looks good. There is only one question:

2023-05-31 13:03 UTC, dersim-davaod commented on Sleep Tracker/SleepTracker/ViewModel/SleepPageViewModel.swift
> +final class SleepPageViewModel: ObservableObject {
@MikhailKosarev yes, the logic in the `SleepPageViewModel`.
Specifically, the `isSleepInProgress` property contains it.

Does it work incorrectly?

2023-05-31 18:15 UTC, marinkman approved these changes
LGTM

2023-05-31 21:03 UTC, MikhailKosarev commented on Sleep Tracker/SleepTracker/ViewModel/SleepPageViewModel.swift
> +final class SleepPageViewModel: ObservableObject {
Everything is ok

2023-06-01 06:15 UTC, dersim-davaod commented
The `CHANGELOG.md` has been updated.

2023-06-01 07:08 UTC, MikhailKosarev approved these changes
LGTM

2023-06-01 07:10 UTC, merged