Release 0.1.0
ios-course/swiftcowboys-team-project pull request #93
Opened 2023-06-01 15:50 UTC by marinkman

## What?
- Updated `CHANGELOG.md` for the release version 0.1.0
- Updated `RELEASENOTES.md` for the release version 0.1.0
- Set marketing and current project version 0.1.0

## Why?
- To close #57

2023-06-01 16:50 UTC, MikhailKosarev requested changes
One question about the release notes:

2023-06-01 16:50 UTC, MikhailKosarev commented on RELEASENOTES.md
> +- The user can start the application, on the screen he can turn on or off the alarm. When the alarm is turned on, the user can choose an alarm time. Each time the user selects a time in the time pick
Maybe it would be better to write it in a more user-friendly format?
```suggestion
We are pleased to present the first release of the `SleepTracker' app! You can set an alarm by selecting a time. The app will show you the predicted duration of your sleep. If you don't need the alarm clock, you can easily turn it off. 
```

2023-06-01 17:59 UTC, MikhailKosarev commented on RELEASENOTES.md
> +- The user can start the application, on the screen he can turn on or off the alarm. When the alarm is turned on, the user can choose an alarm time. Each time the user selects a time in the time pick
@marinkman I don't think it's necessary, but it's so friendly :)

2023-06-01 18:46 UTC, marinkman commented on RELEASENOTES.md
> +- The user can start the application, on the screen he can turn on or off the alarm. When the alarm is turned on, the user can choose an alarm time. Each time the user selects a time in the time pick
@MikhailKosarev I'll post it in the release.

2023-06-02 08:11 UTC, MikhailKosarev approved these changes
LGTM

2023-06-02 08:11 UTC, MikhailKosarev commented on RELEASENOTES.md
> +   - `During sleep mode`: You can see the time the alarm is set or information that the alarm has not been set. After waking up, you can press the `Stop sleeping` button and go back to `Wake mode`, w
nit: 
```suggestion
   - `During sleep mode`: You can see the alarm time set or information that the alarm has not been set. After waking up, you can press the `Stop sleeping` button and go back to `Wake mode`, where you will see the alarm time set earlier.
```

2023-06-02 09:06 UTC, marinkman commented on RELEASENOTES.md
> +   - `During sleep mode`: You can see the time the alarm is set or information that the alarm has not been set. After waking up, you can press the `Stop sleeping` button and go back to `Wake mode`, w
Fixed.

2023-06-02 10:38 UTC, meschya approved these changes
LGTM

2023-06-02 15:36 UTC, merged